version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    env_file:
      - rt/.env
    volumes:
      - db:/var/lib/postgresql/data

  rt:
    image: reuteras/container-rt:latest
    restart: unless-stopped
    env_file:
      - rt/.env
    ports:
      - "443:443"
    volumes:
      - rt/files:/data:ro
    depends_on:
      - db

volumes:
  db:
  app:
