version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    env_file:
      - rt/.env
    volumes:
      - db:/var/lib/postgresql/data

  rt:
    image: reuteras/container-rt:latest
    restart: unless-stopped
    env_file:
      - rt/.env
    ports:
      - "443:8443"
    volumes:
      - ./rt/files:/data:ro
      - cert:/etc/letsencrypt
    depends_on:
      - db

  cron:
    build:
      context:
        ./cron
    restart: unless-stopped
    env_file:
      - rt/.env
    ports:
      - "80:8080"
    volumes:
      - cert:/etc/letsencrypt
      - backup:/backup
    depends_on:
      - db
      - rt

volumes:
  backup:
  cert:
  db:
