version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    env_file:
      - rt/.env
    volumes:
      - db:/var/lib/postgresql/data

  rt:
    #    image: reuteras/docker-rt:latest
    image: docker-rt-test
    restart: unless-stopped
    env_file:
      - rt/.env
    ports:
      - "443:443"
    volumes:
      - .rt/files:/data:ro
      - .rt/entrypoint.sh:/entrypoint.sh:ro
    depends_on:
      - db

volumes:
  db:
  app:
