version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - POSTGRES_DB=postgres
      - RT_USER=${RT_DB_USER}
      - RT_PASSWORD=${RT_DB_PASS}
      - RT_POSTGRES_DB=${RT_DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  rt:
    #    image: reuteras/docker-rt:latest
    image: docker-rt-test
    restart: unless-stopped
    env_file:
      - rt/.env-dev
    ports:
      - "443:443"
    volumes:
      - ./rt/files-dev:/data:ro
      - ./rt/entrypoint.sh:/entrypoint.sh:ro
    depends_on:
      - db

volumes:
  db:
  app:
